-- Supabase / PostgreSQL Schema for SLR Water Billing System
-- Run this in Supabase SQL Editor to create all tables

-- ============================================================
-- STEP 1: Create ENUM types first
-- ============================================================
CREATE TYPE reading_status_enum AS ENUM ('Normal', 'Locked', 'Malfunction', 'Estimated');

-- ============================================================
-- STEP 2: Create Tables (in order of dependencies)
-- ============================================================

-- Table: roles
CREATE TABLE roles (
  "Role_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Role_Name" VARCHAR(50) NOT NULL
);

-- Table: accounts
CREATE TABLE accounts (
  "AccountID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Username" VARCHAR(100) NOT NULL UNIQUE,
  "Password" VARCHAR(255) NOT NULL,
  "Full_Name" VARCHAR(200),
  "Role_ID" BIGINT REFERENCES roles("Role_ID")
);

-- Table: zones (plural for Supabase convention)
CREATE TABLE zones (
  "Zone_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Zone_Name" VARCHAR(100) NOT NULL
);

-- Table: classifications (plural for Supabase convention)
CREATE TABLE classifications (
  "Classification_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Classification_Name" VARCHAR(100) NOT NULL
);

-- Table: consumer
CREATE TABLE consumer (
  "Consumer_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "First_Name" VARCHAR(100),
  "Last_Name" VARCHAR(100),
  "Address" VARCHAR(255),
  "Zone_ID" BIGINT REFERENCES zones("Zone_ID"),
  "Classification_ID" BIGINT REFERENCES classifications("Classification_ID"),
  "Login_ID" BIGINT REFERENCES accounts("AccountID"),
  "Account_Number" VARCHAR(50) UNIQUE,
  "Meter_Number" VARCHAR(50),
  "Status" VARCHAR(20) DEFAULT 'Active',
  "Contact_Number" VARCHAR(20),
  "Connection_Date" DATE
);

-- Table: meters (plural for Supabase convention)
CREATE TABLE meters (
  "Meter_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Consumer_ID" BIGINT UNIQUE REFERENCES consumer("Consumer_ID"),
  "Meter_Serial_Number" VARCHAR(100),
  "Meter_Size" VARCHAR(50)
);

-- Table: meterreaders (for meter reader employee details)
CREATE TABLE meterreaders (
  "Meter_Reader_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Account_ID" BIGINT REFERENCES accounts("AccountID"),
  "First_Name" VARCHAR(100),
  "Last_Name" VARCHAR(100),
  "Contact_Number" VARCHAR(20),
  "Email" VARCHAR(100)
);

-- Table: routes
CREATE TABLE routes (
  "Route_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Meter_Reader_ID" BIGINT REFERENCES meterreaders("Meter_Reader_ID"),
  "Zone_ID" BIGINT REFERENCES zones("Zone_ID")
);

-- Table: meterreadings
CREATE TABLE meterreadings (
  "Reading_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Route_ID" BIGINT REFERENCES routes("Route_ID"),
  "Consumer_ID" BIGINT REFERENCES consumer("Consumer_ID"),
  "Meter_ID" BIGINT REFERENCES meters("Meter_ID"),
  "Meter_Reader_ID" BIGINT,
  "Created_Date" TIMESTAMPTZ DEFAULT NOW(),
  "Reading_Status" reading_status_enum DEFAULT 'Normal',
  "Previous_Reading" NUMERIC(10, 2) DEFAULT 0,
  "Current_Reading" NUMERIC(10, 2) DEFAULT 0,
  "Consumption" NUMERIC(10, 2) DEFAULT 0,
  "Notes" TEXT,
  "Status" VARCHAR(20) DEFAULT 'Pending',
  "Reading_Date" DATE DEFAULT CURRENT_DATE
);

-- Table: bills
CREATE TABLE bills (
  "Bill_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Consumer_ID" BIGINT REFERENCES consumer("Consumer_ID"),
  "Reading_ID" BIGINT REFERENCES meterreadings("Reading_ID"),
  "Billing_Officer_ID" BIGINT REFERENCES accounts("AccountID"),
  "Billing_Month" VARCHAR(20),
  "Amount_Due" NUMERIC(10, 2) DEFAULT 0,
  "Penalty" NUMERIC(10, 2) DEFAULT 0,
  "Previous_Balance" NUMERIC(10, 2) DEFAULT 0,
  "Previous_Penalty" NUMERIC(10, 2) DEFAULT 0,
  "Connection_Fee" NUMERIC(10, 2) DEFAULT 0,
  "Total_Amount" NUMERIC(10, 2) DEFAULT 0,
  "Due_Date" DATE,
  "Payment_Status" VARCHAR(20) DEFAULT 'Unpaid',
  "Bill_Date" DATE DEFAULT CURRENT_DATE
);

-- Table: payments (plural for Supabase convention)
CREATE TABLE payments (
  "PaymentID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ConsumerID" BIGINT REFERENCES consumer("Consumer_ID"),
  "BillID" BIGINT REFERENCES bills("Bill_ID"),
  "PaymentDate" DATE DEFAULT CURRENT_DATE,
  "AmountPaid" NUMERIC(10, 2) DEFAULT 0,
  "ORNumber" VARCHAR(50),
  "Status" VARCHAR(20) DEFAULT 'Verified',
  "Payment_Method" VARCHAR(50) DEFAULT 'Cash',
  "Reference_Number" VARCHAR(100),
  "Validated_By" BIGINT,
  "Validated_Date" TIMESTAMPTZ
);

-- Table: reading_schedules (for meter reading assignments)
CREATE TABLE reading_schedules (
  "Schedule_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Schedule_Date" DATE NOT NULL,
  "Zone_ID" BIGINT REFERENCES zones("Zone_ID"),
  "Meter_Reader_ID" BIGINT REFERENCES accounts("AccountID"),
  "Status" VARCHAR(20) DEFAULT 'Scheduled',
  "Notes" TEXT,
  "Created_By" BIGINT REFERENCES accounts("AccountID"),
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

-- Table: waterrates
CREATE TABLE waterrates (
  "RateID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MinimumRate" NUMERIC(10, 2) DEFAULT 0,
  "Rate11to20" NUMERIC(10, 2) DEFAULT 0,
  "Rate21to30" NUMERIC(10, 2) DEFAULT 0,
  "Rate31to40" NUMERIC(10, 2) DEFAULT 0,
  "Rate41Plus" NUMERIC(10, 2) DEFAULT 0,
  "EffectiveDate" DATE DEFAULT CURRENT_DATE,
  "ModifiedBy" BIGINT REFERENCES accounts("AccountID"),
  "ModifiedDate" TIMESTAMPTZ DEFAULT NOW()
);

-- Table: ledger (Digital Ledger - Water Service Record)
CREATE TABLE ledger (
  "Ledger_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Consumer_ID" BIGINT REFERENCES consumer("Consumer_ID"),
  "Ledger_Date" DATE NOT NULL,
  "Billing_Month" VARCHAR(20),
  "Meter_Reading" NUMERIC(10, 2) DEFAULT 0,
  "Consumption" NUMERIC(10, 2) DEFAULT 0,
  "Water_Billing" NUMERIC(10, 2) DEFAULT 0,
  "Penalty" NUMERIC(10, 2) DEFAULT 0,
  "Meter_Charges" NUMERIC(10, 2) DEFAULT 0,
  "Payment" NUMERIC(10, 2) DEFAULT 0,
  "Receipt_Number" VARCHAR(50),
  "Balance" NUMERIC(10, 2) DEFAULT 0,
  "Bill_ID" BIGINT REFERENCES bills("Bill_ID"),
  "Payment_ID" BIGINT REFERENCES payments("PaymentID"),
  "Reading_ID" BIGINT REFERENCES meterreadings("Reading_ID"),
  "Created_By" BIGINT REFERENCES accounts("AccountID"),
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

-- Table: system_settings (System-wide configuration)
CREATE TABLE system_settings (
  "Setting_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "System_Name" VARCHAR(200),
  "Currency" VARCHAR(10),
  "Due_Date_Days" INTEGER DEFAULT 30,
  "Late_Fee_Percent" NUMERIC(5, 2) DEFAULT 0,
  "Updated_At" TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- STEP 3: Create Indexes for performance
-- ============================================================
CREATE INDEX idx_bills_status ON bills("Payment_Status");
CREATE INDEX idx_bills_consumer ON bills("Consumer_ID");
CREATE INDEX idx_consumer_status ON consumer("Status");
CREATE INDEX idx_consumer_zone ON consumer("Zone_ID");
CREATE INDEX idx_reading_consumer ON meterreadings("Consumer_ID");
CREATE INDEX idx_reading_date ON meterreadings("Reading_Date");
CREATE INDEX idx_payment_consumer ON payments("ConsumerID");
CREATE INDEX idx_payment_date ON payments("PaymentDate");
CREATE INDEX idx_ledger_consumer ON ledger("Consumer_ID");
CREATE INDEX idx_ledger_date ON ledger("Ledger_Date");

-- ============================================================
-- STEP 4: Insert Initial Data (Roles)
-- ============================================================
INSERT INTO roles ("Role_Name") VALUES 
  ('Admin'),
  ('Meter Reader'),
  ('Billing Officer'),
  ('Cashier'),
  ('Consumer');

-- ============================================================
-- STEP 5: Insert Sample Zones
-- ============================================================
INSERT INTO zones ("Zone_Name") VALUES 
  ('Zone 1'),
  ('Zone 2'),
  ('Zone 3'),
  ('Zone 4'),
  ('Zone 5');

-- ============================================================
-- STEP 6: Insert Sample Classifications
-- ============================================================
INSERT INTO classifications ("Classification_Name") VALUES 
  ('Residential'),
  ('Commercial'),
  ('Industrial'),
  ('Government');

-- ============================================================
-- STEP 7: Insert Default Water Rates
-- ============================================================
INSERT INTO waterrates ("MinimumRate", "Rate11to20", "Rate21to30", "Rate31to40", "Rate41Plus", "EffectiveDate") VALUES 
  (150.00, 15.00, 20.00, 25.00, 30.00, CURRENT_DATE);

-- ============================================================
-- STEP 8: Insert Admin Account (Change password after setup!)
-- ============================================================
INSERT INTO accounts ("Username", "Password", "Role_ID") VALUES 
  ('admin', 'admin123', 1);

-- ============================================================
-- STEP 9: Enable Row Level Security (RLS) - Optional but recommended
-- ============================================================
-- You can enable RLS later for production security
-- ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE consumer ENABLE ROW LEVEL SECURITY;
-- etc.
