-- =========================================================
-- San Lorenzo Water Billing: Current Schema Backup
-- Target schema: water_billing
-- Purpose: structure-only backup for PostgreSQL/Supabase
-- =========================================================

CREATE SCHEMA IF NOT EXISTS water_billing;
SET search_path TO water_billing, public;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------- Core lookup ----------
CREATE TABLE IF NOT EXISTS roles (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS zone (
  zone_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS classification (
  classification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classification_name VARCHAR(50) NOT NULL UNIQUE
);

-- ---------- Accounts ----------
CREATE TABLE IF NOT EXISTS accounts (
  account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  full_name TEXT,
  email VARCHAR(255),
  contact_number VARCHAR(20),
  profile_picture_url TEXT,
  auth_user_id UUID UNIQUE,
  role_id INTEGER NOT NULL,
  account_status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_site_id VARCHAR(120),
  sync_status VARCHAR(20) NOT NULL DEFAULT 'synced',
  CONSTRAINT accounts_account_status_check
    CHECK (account_status IN ('Pending', 'Approved', 'Rejected', 'Active', 'Inactive')),
  CONSTRAINT fk_accounts_role
    FOREIGN KEY (role_id) REFERENCES roles(role_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

-- ---------- Master settings ----------
CREATE TABLE IF NOT EXISTS admin_settings (
  settings_id INTEGER PRIMARY KEY,
  system_name VARCHAR(255) NOT NULL,
  currency VARCHAR(20) NOT NULL DEFAULT 'PHP',
  due_date_days INTEGER NOT NULL DEFAULT 15,
  late_fee NUMERIC(8,2) NOT NULL DEFAULT 10.00,
  modified_by INTEGER,
  modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_admin_settings_modified_by
    FOREIGN KEY (modified_by) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS billing_settings (
  setting_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  penalty_percent NUMERIC(5,2) NOT NULL DEFAULT 10.00,
  due_days INTEGER NOT NULL DEFAULT 15,
  effective_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------- Consumer + metering ----------
CREATE TABLE IF NOT EXISTS consumer (
  consumer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100),
  last_name VARCHAR(100) NOT NULL,
  address TEXT NOT NULL,
  purok VARCHAR(100),
  barangay VARCHAR(100),
  municipality VARCHAR(100) DEFAULT 'San Lorenzo Ruiz',
  zip_code VARCHAR(10) DEFAULT '4610',
  zone_id INTEGER,
  classification_id INTEGER,
  login_id INTEGER NOT NULL UNIQUE,
  account_number VARCHAR(50) UNIQUE,
  status VARCHAR(20) NOT NULL DEFAULT 'Active',
  contact_number VARCHAR(20),
  connection_date TIMESTAMP,
  meter_number TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_site_id VARCHAR(120),
  sync_status VARCHAR(20) NOT NULL DEFAULT 'synced',
  CONSTRAINT consumer_status_check
    CHECK (status IN ('Pending', 'Active', 'Inactive')),
  CONSTRAINT fk_consumer_zone
    FOREIGN KEY (zone_id) REFERENCES zone(zone_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_consumer_classification
    FOREIGN KEY (classification_id) REFERENCES classification(classification_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_consumer_login
    FOREIGN KEY (login_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS meter (
  meter_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  consumer_id INTEGER NOT NULL,
  meter_serial_number VARCHAR(100) NOT NULL UNIQUE,
  meter_size VARCHAR(50),
  meter_status VARCHAR(20) NOT NULL DEFAULT 'Active',
  installed_date TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_site_id VARCHAR(120),
  sync_status VARCHAR(20) NOT NULL DEFAULT 'synced',
  CONSTRAINT meter_status_check
    CHECK (meter_status IN ('Active', 'Inactive', 'Defective', 'Disconnected')),
  CONSTRAINT fk_meter_consumer
    FOREIGN KEY (consumer_id) REFERENCES consumer(consumer_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS route (
  route_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meter_reader_id INTEGER NOT NULL,
  zone_id INTEGER NOT NULL,
  CONSTRAINT fk_route_meter_reader
    FOREIGN KEY (meter_reader_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_route_zone
    FOREIGN KEY (zone_id) REFERENCES zone(zone_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS meterreadings (
  reading_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  route_id INTEGER,
  consumer_id INTEGER NOT NULL,
  meter_id INTEGER,
  meter_reader_id INTEGER,
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reading_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  previous_reading NUMERIC(12,2) NOT NULL DEFAULT 0,
  current_reading NUMERIC(12,2) NOT NULL DEFAULT 0,
  consumption NUMERIC(12,2) NOT NULL DEFAULT 0,
  excess_consumption NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'Active',
  reading_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_site_id VARCHAR(120),
  sync_status VARCHAR(20) NOT NULL DEFAULT 'synced',
  CONSTRAINT meterreadings_reading_status_check
    CHECK (reading_status IN ('Pending', 'Normal', 'Recorded', 'Verified', 'Rejected')),
  CONSTRAINT meterreadings_status_check
    CHECK (status IN ('Active', 'Inactive')),
  CONSTRAINT chk_meterreadings_values
    CHECK (
      current_reading >= previous_reading
      AND consumption >= 0
      AND excess_consumption >= 0
    ),
  CONSTRAINT fk_meterreadings_route
    FOREIGN KEY (route_id) REFERENCES route(route_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_meterreadings_consumer
    FOREIGN KEY (consumer_id) REFERENCES consumer(consumer_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_meterreadings_meter
    FOREIGN KEY (meter_id) REFERENCES meter(meter_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_meterreadings_reader
    FOREIGN KEY (meter_reader_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS reading_schedule (
  schedule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_date DATE NOT NULL,
  zone_id INTEGER NOT NULL,
  meter_reader_id INTEGER,
  status VARCHAR(50) NOT NULL DEFAULT 'Scheduled',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT reading_schedule_unique UNIQUE (schedule_date, zone_id),
  CONSTRAINT fk_reading_schedule_zone
    FOREIGN KEY (zone_id) REFERENCES zone(zone_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_reading_schedule_meter_reader
    FOREIGN KEY (meter_reader_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

-- ---------- Billing ----------
CREATE TABLE IF NOT EXISTS bills (
  bill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  consumer_id INTEGER NOT NULL,
  reading_id INTEGER NOT NULL UNIQUE,
  billing_officer_id INTEGER,
  billing_month VARCHAR(30),
  date_covered_from TIMESTAMP,
  date_covered_to TIMESTAMP,
  bill_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  due_date TIMESTAMP,
  disconnection_date TIMESTAMP,
  class_cost NUMERIC(12,2) NOT NULL DEFAULT 0,
  water_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
  meter_maintenance_fee NUMERIC(12,2) NOT NULL DEFAULT 0,
  connection_fee NUMERIC(12,2) NOT NULL DEFAULT 0,
  amount_due NUMERIC(12,2) NOT NULL DEFAULT 0,
  previous_balance NUMERIC(12,2) NOT NULL DEFAULT 0,
  previous_penalty NUMERIC(12,2) NOT NULL DEFAULT 0,
  penalty NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_after_due_date NUMERIC(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'Unpaid',
  setting_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_site_id VARCHAR(120),
  sync_status VARCHAR(20) NOT NULL DEFAULT 'synced',
  CONSTRAINT bills_status_check
    CHECK (status IN ('Unpaid', 'Partially Paid', 'Paid', 'Overdue', 'Cancelled')),
  CONSTRAINT fk_bills_consumer
    FOREIGN KEY (consumer_id) REFERENCES consumer(consumer_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_bills_reading
    FOREIGN KEY (reading_id) REFERENCES meterreadings(reading_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_bills_billing_officer
    FOREIGN KEY (billing_officer_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_bills_setting
    FOREIGN KEY (setting_id) REFERENCES billing_settings(setting_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS payment (
  payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  consumer_id INTEGER NOT NULL,
  bill_id INTEGER NOT NULL,
  payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  amount_paid NUMERIC(12,2) NOT NULL,
  or_number VARCHAR(100),
  payment_method VARCHAR(50) NOT NULL,
  reference_number VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  validated_by INTEGER,
  validated_date TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_site_id VARCHAR(120),
  sync_status VARCHAR(20) NOT NULL DEFAULT 'synced',
  CONSTRAINT payment_status_check
    CHECK (status IN ('Pending', 'Validated', 'Rejected', 'Voided')),
  CONSTRAINT chk_payment_amount
    CHECK (amount_paid >= 0),
  CONSTRAINT fk_payment_consumer
    FOREIGN KEY (consumer_id) REFERENCES consumer(consumer_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_payment_bill
    FOREIGN KEY (bill_id) REFERENCES bills(bill_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_payment_validated_by
    FOREIGN KEY (validated_by) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ledger_entry (
  ledger_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  consumer_id INTEGER NOT NULL,
  transaction_type VARCHAR(50) NOT NULL,
  reference_id INTEGER,
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  balance NUMERIC(12,2) NOT NULL DEFAULT 0,
  transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_site_id VARCHAR(120),
  sync_status VARCHAR(20) NOT NULL DEFAULT 'synced',
  CONSTRAINT fk_ledger_entry_consumer
    FOREIGN KEY (consumer_id) REFERENCES consumer(consumer_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS waterrates (
  rate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  minimum_cubic INTEGER NOT NULL DEFAULT 10,
  minimum_rate NUMERIC(12,2) NOT NULL DEFAULT 75.00,
  excess_rate_per_cubic NUMERIC(12,2) NOT NULL DEFAULT 7.50,
  effective_date DATE NOT NULL,
  classification_id INTEGER,
  modified_by INTEGER,
  modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_waterrates_classification
    FOREIGN KEY (classification_id) REFERENCES classification(classification_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_waterrates_modified_by
    FOREIGN KEY (modified_by) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

-- ---------- Tickets + audit ----------
CREATE TABLE IF NOT EXISTS connection_ticket (
  ticket_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  consumer_id INTEGER,
  account_id INTEGER NOT NULL,
  ticket_number VARCHAR(100) NOT NULL UNIQUE,
  application_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  connection_type VARCHAR(50) NOT NULL,
  requirements_submitted TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  inspection_date TIMESTAMP,
  approved_by INTEGER,
  approved_date TIMESTAMP,
  remarks TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_site_id VARCHAR(120),
  sync_status VARCHAR(20) NOT NULL DEFAULT 'synced',
  CONSTRAINT connection_ticket_status_check
    CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Processing', 'Completed')),
  CONSTRAINT fk_connection_ticket_consumer
    FOREIGN KEY (consumer_id) REFERENCES consumer(consumer_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT fk_connection_ticket_account
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_connection_ticket_approved_by
    FOREIGN KEY (approved_by) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS password_reset (
  reset_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL,
  reset_token VARCHAR(255) NOT NULL UNIQUE,
  expiration_time TIMESTAMP NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT password_reset_status_check
    CHECK (status IN ('Active', 'Used', 'Expired', 'Pending', 'Cancelled')),
  CONSTRAINT fk_password_reset_account
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS account_review_log (
  review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL,
  reviewed_by INTEGER NOT NULL,
  review_status VARCHAR(20) NOT NULL,
  review_date TIMESTAMP,
  remarks TEXT,
  CONSTRAINT account_review_log_review_status_check
    CHECK (review_status IN ('Pending', 'Approved', 'Rejected')),
  CONSTRAINT fk_account_review_log_account
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_account_review_log_reviewed_by
    FOREIGN KEY (reviewed_by) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS backuplogs (
  backup_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  backup_name VARCHAR(255) NOT NULL,
  backup_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  backup_size VARCHAR(100),
  backup_type VARCHAR(50),
  created_by INTEGER,
  CONSTRAINT fk_backuplogs_created_by
    FOREIGN KEY (created_by) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS error_logs (
  error_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  error_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  severity VARCHAR(20) NOT NULL,
  module VARCHAR(100),
  error_message TEXT NOT NULL,
  user_id INTEGER,
  status VARCHAR(20) DEFAULT 'Open',
  CONSTRAINT error_logs_status_check
    CHECK (status IN ('Open', 'Resolved', 'Ignored')),
  CONSTRAINT fk_error_logs_user
    FOREIGN KEY (user_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS system_logs (
  log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL,
  role VARCHAR(50),
  action TEXT NOT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_system_logs_account
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS consumer_concerns (
  concern_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_id UUID DEFAULT gen_random_uuid() NOT NULL,
  consumer_id INTEGER,
  account_id INTEGER NOT NULL,
  category VARCHAR(50) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  priority VARCHAR(20) NOT NULL DEFAULT 'Normal',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP,
  resolved_by INTEGER,
  remarks TEXT,
  CONSTRAINT consumer_concerns_status_check
    CHECK (status IN ('Pending', 'In Progress', 'Resolved', 'Closed', 'Rejected')),
  CONSTRAINT consumer_concerns_priority_check
    CHECK (priority IN ('Low', 'Normal', 'High', 'Urgent')),
  CONSTRAINT fk_consumer_concerns_consumer
    FOREIGN KEY (consumer_id) REFERENCES consumer(consumer_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT fk_consumer_concerns_account
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_consumer_concerns_resolved_by
    FOREIGN KEY (resolved_by) REFERENCES accounts(account_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public_contact_messages (
  message_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(160) NOT NULL,
  barangay VARCHAR(120) NOT NULL,
  contact_number VARCHAR(20) NOT NULL,
  subject VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP WITHOUT TIME ZONE,
  reviewed_by INTEGER,
  remarks TEXT,
  CONSTRAINT public_contact_messages_status_check
    CHECK (status IN ('Pending', 'In Progress', 'Resolved', 'Closed'))
);

-- ---------- Zone coverage ----------
CREATE TABLE IF NOT EXISTS zone_coverage (
  config_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id INTEGER NOT NULL,
  barangay VARCHAR(120) NOT NULL,
  purok_count INTEGER NOT NULL DEFAULT 0,
  is_split BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT zone_coverage_unique UNIQUE (zone_id, barangay),
  CONSTRAINT zone_coverage_zone_id_fkey
    FOREIGN KEY (zone_id) REFERENCES zone(zone_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION set_zone_coverage_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_zone_coverage_updated_at ON zone_coverage;
CREATE TRIGGER trg_zone_coverage_updated_at
BEFORE UPDATE ON zone_coverage
FOR EACH ROW
EXECUTE FUNCTION set_zone_coverage_updated_at();

-- ---------- Sync metadata ----------
CREATE TABLE IF NOT EXISTS sync_conflicts (
  conflict_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR(100) NOT NULL,
  direction VARCHAR(50) NOT NULL,
  conflict_type VARCHAR(50) NOT NULL,
  primary_key_name VARCHAR(100),
  primary_key_value TEXT,
  business_key TEXT,
  reason TEXT NOT NULL,
  source_record JSONB,
  existing_record JSONB,
  status VARCHAR(20) NOT NULL DEFAULT 'Open',
  detected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION set_sync_row_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

-- ---------- Indexes ----------
CREATE INDEX IF NOT EXISTS idx_consumer_login_id ON consumer(login_id);
CREATE INDEX IF NOT EXISTS idx_consumer_account_number ON consumer(account_number);
CREATE INDEX IF NOT EXISTS idx_meter_consumer_id ON meter(consumer_id);
CREATE INDEX IF NOT EXISTS idx_route_meter_reader_id ON route(meter_reader_id);
CREATE INDEX IF NOT EXISTS idx_meterreadings_consumer_id ON meterreadings(consumer_id);
CREATE INDEX IF NOT EXISTS idx_meterreadings_meter_id ON meterreadings(meter_id);
CREATE INDEX IF NOT EXISTS idx_bills_consumer_id ON bills(consumer_id);
CREATE INDEX IF NOT EXISTS idx_payment_consumer_id ON payment(consumer_id);
CREATE INDEX IF NOT EXISTS idx_payment_bill_id ON payment(bill_id);
CREATE INDEX IF NOT EXISTS idx_ledger_entry_consumer_id ON ledger_entry(consumer_id);
CREATE INDEX IF NOT EXISTS idx_connection_ticket_account_id ON connection_ticket(account_id);
CREATE INDEX IF NOT EXISTS idx_connection_ticket_consumer_id ON connection_ticket(consumer_id);
CREATE INDEX IF NOT EXISTS idx_system_logs_account_id ON system_logs(account_id);
CREATE INDEX IF NOT EXISTS idx_error_logs_user_id ON error_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_consumer_concerns_account_id ON consumer_concerns(account_id);
CREATE INDEX IF NOT EXISTS idx_consumer_concerns_consumer_id ON consumer_concerns(consumer_id);
CREATE INDEX IF NOT EXISTS idx_public_contact_messages_created_at ON public_contact_messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_public_contact_messages_status ON public_contact_messages(status);
CREATE INDEX IF NOT EXISTS idx_zone_coverage_zone_id ON zone_coverage(zone_id);
CREATE INDEX IF NOT EXISTS idx_zone_coverage_barangay ON zone_coverage(barangay);
CREATE INDEX IF NOT EXISTS idx_reading_schedule_zone_date ON reading_schedule(zone_id, schedule_date);
